Cria avaliador Stylelint em GitHub Action
betrybe/stylelint-linter-action pull request #1
Opened 2020-11-09 13:13 UTC by jeanpsv

2020-11-11 17:17 UTC, norbajunior approved these changes

2020-11-11 19:36 UTC, raigons approved these changes

2020-11-11 19:36 UTC, raigons commented on __tests__/fixtures/projects/front-end/main.css
> +  width: 100pixels;
quallequié a desse `pixels`?  diferente....

2020-11-11 21:33 UTC, inaC requested changes

2020-11-11 21:33 UTC, inaC commented on package.json
> +  "description": "JavaScript Linter Action",
```suggestion
  "description": "Stylelint Linter Action",
```

2020-11-11 21:33 UTC, inaC commented on runStylelintWithConfigFile.js
> +      '--ignore-disables',
E se não houver arquivo css para ser analisado, o comando falharia, não? Eu fui dar uma olhada na documentação e tem uma [opção](https://stylelint.io/user-guide/usage/cli#--allow-empty-input---aei) para que o stylelint não retorne erro caso arquivos não sejam encontrados

2020-11-11 21:33 UTC, inaC commented on feedbackMessage.js
> +    warningIssues = buildIssuesMessage(source, warning, root);
Você poderia reduzir essas linhas para:
```suggestion
    const { source, error, warning } = currentValue;
    const errorIssues = buildIssuesMessage(source, error, root);
    const warningIssues = buildIssuesMessage(source, warning, root);
```

2020-11-11 21:33 UTC, inaC commented on feedbackMessage.js
> +  let messages = [];
Como você não está reatribuindo `messages`, você poderia defini-la como `const`:
```suggestion
  const messages = [];
```

2020-11-11 21:33 UTC, inaC commented on feedbackMessage.js
> +const feedBackTitleMessage = (issueType, count) => {
```suggestion
const feedbackTitleMessage = (issueType, count) => {
```
As sugestões para mudar as chamadas se encontram em [1](https://github.com/betrybe/stylelint-linter-action/pull/1/files#r521617676) e [2](https://github.com/betrybe/stylelint-linter-action/pull/1/files#r521617778)

2020-11-11 21:33 UTC, inaC commented on feedbackMessage.js
> +  feedbackMessage.push(feedBackTitleMessage('erro', errorCount));
```suggestion
  feedbackMessage.push(feedbackTitleMessage('erro', errorCount));
```

2020-11-11 21:33 UTC, inaC commented on feedbackMessage.js
> +  feedbackMessage.push(feedBackTitleMessage('aviso', warningCount));
```suggestion
  feedbackMessage.push(feedbackTitleMessage('aviso', warningCount));
```

2020-11-11 21:33 UTC, inaC commented on __tests__/runStylelint.test.js
> +        .mockReturnValueOnce({ status: 0, outcomes: stylelintResultWithOneError })
Se o status da análise é `0` para o projeto `front-end1`, você não deveria fazer o require da fixture `fixtures/stylelint-results/oneError.json`, tipo o seguinte?

```javascript
const stylelintResultWithoutError = require('./fixtures/stylelint-results/noError.json');
```
Depois, você precisaria mudar essa linha para:
```suggestion
        .mockReturnValueOnce({ status: 0, outcomes: stylelintResultWithoutError })
```

2020-11-11 21:33 UTC, inaC commented on __tests__/fixtures/stylelint-results/multipleErrorsAndWarningsMultipleFiles.json
> +[
Esse arquivo aparentemente não está sendo usado em testes que validam o comportamento da mensagem de feedback

2020-11-12 10:34 UTC, jeanpsv commented on __tests__/fixtures/projects/front-end/main.css
> +  width: 100pixels;
@raigons criei essa linha justamente para falhar na avaliação do Stylelint no check que verifica as unidades.

2020-11-12 10:57 UTC, jeanpsv commented on runStylelintWithConfigFile.js
> +      '--ignore-disables',
boa @inaC vou testar isso aqui

2020-11-12 11:05 UTC, jeanpsv commented on __tests__/fixtures/stylelint-results/multipleErrorsAndWarningsMultipleFiles.json
> +[
uai, vou ver isso aqui tbm.

2020-11-12 11:32 UTC, jeanpsv commented on __tests__/fixtures/stylelint-results/multipleErrorsAndWarningsMultipleFiles.json
> +[
vou implementar mais um teste

2020-11-12 11:47 UTC, jeanpsv commented on runStylelintWithConfigFile.js
> +      '--ignore-disables',
ajustei isso, iria dar problema mesmo.

2020-11-12 11:47 UTC, jeanpsv commented on __tests__/fixtures/stylelint-results/multipleErrorsAndWarningsMultipleFiles.json
> +[
implementei um teste para ele.

2020-11-12 12:49 UTC, inaC requested changes

2020-11-12 12:49 UTC, inaC commented on __tests__/feedbackMessage.test.js
> +      console.log(buildFeedbackMessage(multipleErrosAndWarningsMultipleFiles, './'))
```suggestion
```

2020-11-12 13:06 UTC, jeanpsv commented on __tests__/feedbackMessage.test.js
> +      console.log(buildFeedbackMessage(multipleErrosAndWarningsMultipleFiles, './'))
🤦 🤦 🤦 🤦 🤦 🤦

2020-11-12 13:09 UTC, inaC commented on __tests__/feedbackMessage.test.js
> +      console.log(buildFeedbackMessage(multipleErrosAndWarningsMultipleFiles, './'))
😂

2020-11-12 13:09 UTC, inaC approved these changes

2020-11-12 15:12 UTC, LeandroLM approved these changes

2020-11-12 15:12 UTC, LeandroLM commented on README.md
> +In order to configure the `Stylelint` analysis for your project, you must create a `.stylelintrc.json` file at the root of your project. Therefore, beware the following:
```suggestion
In order to configure the `Stylelint` analysis for your project, you must create a `.stylelintrc.json` file at the root of your project. Therefore, beware of the following:
```

2020-11-13 16:50 UTC, hurrycaner approved these changes

2020-11-17 12:43 UTC, eucleciojosias approved these changes

2020-11-17 17:44 UTC, inaC commented on README.md
> +  - uses: actions/setup-node@v1.4.3
Antes que a gente se esqueça, já poderia mudar a versão do setup-node no seu pr @jeanpsv 
```suggestion
  - uses: actions/setup-node@v1.4.4
```

2020-11-17 18:07 UTC, merged