imp: recebe número da PR como input
betrybe/stylelint-linter-action pull request #2
Opened 2021-01-22 19:59 UTC by eucleciojosias

Devido as alterações na [LEARN-869](https://trybe.atlassian.net/browse/LEARN-869?atlOrigin=eyJpIjoiNjk5MjBkZDIzNTM2NDY5NmExMGJjYmRjN2NlZDAzYjAiLCJwIjoiaiJ9) e como o _workflow_ é disparado via **Github App Selfhosted**, a envvar `GITHUB_ACTOR` não poderá ser usada para pegar o **username** da pessoa estudante. Além disso, o **número** da Pull Request não vem no contexto do evento da _action_. Foi modificado para estes dados serem enviados pelo Github App via _input_. Assim sendo, será necessário modificar os avaliadores para o novo formato.

2021-01-25 12:27 UTC, gknedo approved these changes

2021-01-25 17:57 UTC, jeanpsv approved these changes

2021-01-26 16:45 UTC, inaC requested changes

2021-01-26 16:45 UTC, inaC commented on README.md
> +**P.S.:** Github actions will run `dist/index.js` to execute this action, so you must to run `npm run pack`if you want apply any changes.
```suggestion
⚠️ Github actions will run `dist/index.js` to execute this action, so you *must run* `npm run pack` and commit the changes made at `dist/index.js` if you want to apply any changes. ⚠️
```

2021-01-26 19:09 UTC, inaC approved these changes

2021-02-01 22:39 UTC, merged