fix: ignora arquivos do github actions
betrybe/stylelint-linter-action pull request #3
Opened 2021-08-06 18:57 UTC by eucleciojosias

2021-08-10 12:25 UTC, jeanpsv reviewed
@eucleciojosias os testes estão falhando

2021-08-10 21:00 UTC, inaC requested changes
@eucleciojosias, o stylelint aparentemente suporta [especificar via terminal o caminho](https://stylelint.io/user-guide/usage/cli#--ignore-path--i) de um arquivo contendo os padrões de arquivos a serem ignorados. Isso resolveria o problema em questão deste PR, não?

2021-08-10 21:00 UTC, inaC commented on __tests__/findFilesBy.test.js
> +      .mockReturnValueOnce(false)
Por que o primeiro retorno mockado deve ser falso?

2021-08-10 21:00 UTC, inaC commented on findFilesBy.js
> +      .split('\n')
Seria necessário considerar somente as linhas que definem o padrão a ser ignorado, não? Por exemplo, e se a pessoa colocar no arquivo um comentário? Por exemplo:
```
foo.css
bar.css
# Comentário
```

2021-08-10 21:30 UTC, eucleciojosias commented on __tests__/findFilesBy.test.js
> +      .mockReturnValueOnce(false)
Porque a primeira vez vai buscar pelo `.styleilintgnore` e quebra o teste

2021-08-10 21:31 UTC, eucleciojosias commented
@inaC foi a primeira coisa que eu tentei, tentei inline, tentei pôr no `.stylelintrc.json`, mas nada funcionava, creio eu que é pelo fato de rodar apontando diretamente para o arquivo, enfim, consegui fazer funcionar não retornando os arquivos nessa função e deu boa.

2021-08-10 21:34 UTC, eucleciojosias commented on findFilesBy.js
> +      .split('\n')
Vou tentar fazer um filtro, mas, creio eu, que independentemente de trazer comentários e afins o `minimatch` não ia dar match e não interferiria

2021-08-11 17:45 UTC, jeanpsv approved these changes

2021-08-11 21:26 UTC, eucleciojosias commented on findFilesBy.js
> +      .split('\n')
A gente fez testes e viu que o `.stylelintignore` já funciona, apenas para a pasta `.github` que não, então a solução foca nisso

2021-08-11 22:48 UTC, inaC reviewed
Agora que adicionou esse hook de pre-commit, não seria mais necessário ter [este aviso no README](https://github.com/betrybe/stylelint-linter-action#development), o que acha de removê-lo? ❤️

2021-08-12 13:12 UTC, inaC approved these changes

2021-08-12 13:15 UTC, merged